index/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [

        path('',views.index,name="index"),
        ]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls',namespace='index')),
    path('sales/',include('sales.urls',namespace='sales')),
    path('reports/',include('reports.urls',namespace='reports')),
    path('profiles/',include('profiles.urls',namespace='profiles')),
]

urlpatterns += static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
        path('accounts/login/',views.loginview,name='login'),
        path('accounts/logout/',views.logoutview,name='logout'),
        path('accounts/signup/',views.signupview,name='signup'),
        path('accounts/profile/',views.home,name='home'),
        path('accounts/profile/change_profile_pic/',views.edit_profile_pic,name="edit_profile_pic"),
        ]

profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    CHOICES = (
            ('org','organization'),
            ('staff','staff'),
            )
    user_type = models.CharField(max_length=12,choices=CHOICES,blank=False,null=False)


class Organization(models.Model):

    name = models.CharField(max_length=30)
    logo = models.ImageField(upload_to="logos",default="no_picture.png")
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    public_key = models.CharField(max_length=9)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"profile of {self.user.username}"    

class Staff(models.Model):

    organization = models.ForeignKey(Organization,models.CASCADE)
    user = models.OneToOneField(CustomUser,on_delete = models.CASCADE)
    bio = models.TextField(default="no bio...")
    avatar = models.ImageField(upload_to="avartars",default="no_picture.png")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"profile of {self.user.username}"

profiles/forms.py
from .models import CustomUser
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=25,widget=forms.PasswordInput)

class SignupForm(forms.ModelForm):
    public_key = forms.CharField(max_length=9)
    class Meta:
        model = CustomUser
        fields = ["username","email","user_type","password"]
        widgets = {
                'password':forms.PasswordInput,
                'user_type':forms.RadioSelect,
                }

    def clean_public_key(self):
        data = self.cleaned_data['public_key']
        if not data and self.cleaned_data['user_type']=='staff':
            raise forms.ValidationError("this field is required")
        return data

profiles/views.py
from django.shortcuts import render

from .models import CustomUser, Organization, Staff
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import redirect,reverse
from .forms import LoginForm,SignupForm
from django.urls import resolve
from django.urls.exceptions import Resolver404
from urllib.parse import urlparse
from .utils import get_org
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required
def home(request):
    return render(request,"profiles/home.html")

@login_required
def edit_profile(request):
    form = "work on this later"
    context = {
            "form":form,
            }
    return render(request,"profile/home.html",context)

@login_required
def edit_profile_pic(request):

    if request.method == "POST":
        fd = request.FILES.get("profile_pic")
        if fd is not None:
            request.user.staff.avatar = fd
            request.user.staff.save()
        return redirect(reverse("profiles:home"))
    else:
        return redirect(reverse("profiles:home")) 

def loginview(request):
    if request.method == "GET":
        form = LoginForm()
        msg = list(messages.get_messages(request))
        context = {
                'login_form':form,
                'msg':msg,
                }
        return render(request,"profiles/login.html",context)

    elif request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cleaned_data = form.clean()
            user = authenticate(username=cleaned_data.get('username'),password=cleaned_data.get('password'))
            if user is not None:
                login(request,user)
                next_url = request.GET.get("next")
                if next_url:
                    try:
                        resolve(urlparse(next_url).path)
                        return redirect(next_url)
                    except Resolver404:
                        return redirect(reverse("index:index"))
                else:
                    return redirect(reverse("index:index"))
            else:
                context = {
                        'error':'Invalid username or password',
                        'login_form':form,
                        }

                return render(request,'profiles/login.html',context)

        else:
            context = {
                    'error':'invalid form data',
                    'login_form':form,
                    }
            return render(request,'profiles/login.html',context)


def logoutview(request):
    try:
        logout(request)
    except:
        pass
    return redirect(reverse("profiles:login"))

def signupview(request):

    form = SignupForm(request.POST or None)

    if request.method == "GET":
        context = {
                'signup_form':form
                }
        return render(request,'profiles/signup.html',context)

    elif request.method == "POST":
        if form.is_valid():
            cld = form.clean()

            if cld.get('user_type')=='org':
                CustomUser.objects.create_user(username=cld.get('username'),email=cld.get('email'),password=cld.get('password'),user_type=cld.get('user_type'))

            elif cld.get('user_type')=='staff':
                instance = CustomUser.objects.create_user(username=cld.get('username'),email=cld.get('email'),password=cld.get('password'),user_type=cld.get('user_type'))
                Staff.objects.create(user=instance,organization=get_org(cld.get('public_key')))

            messages.success(request,"Account Created successfully, proceed to login!")

            return redirect(reverse('profiles:login'))
        else:
            context = {
                    'signup_form':form,
                    'error':'invalid data',
                    }
            return render(request,'profiles/signup.html',context)

            

profiles/templates/profiles/home.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'profiles/css/home.css' %}">
{% endblock style %}
{% block scripts %}
<script src="{% static 'profiles/js/home.js' %}"></script>
{% endblock scripts %}
{% block title %}
Profile
{% endblock title %}

{% block content %}
 <div id="framex" >
   <div id="menubar"><p id="menubar-return">&lt&ltback</p></div>
   <div id="profile-picx-frame">
    <img id="profile-picx" src="{{user.staff.avatar.url}}">
   </div>
 </div>

<div>
 {% if user.staff %}

  <div id="frame1" class="bg-body-tertiary">
   <i class="fa-solid fa-pen-to-square" id="edit-profile-pic">edit pic</i>
    <img id="profile-pic" src="{{user.staff.avatar.url}}">
   
   <form enctype="multipart/form-data" method="POST" action="{% url 'profiles:edit_profile_pic' %}" hidden="true" id="profile_pic_form">
    {% csrf_token %}
   <input name="profile_pic" type="file" accept=".png" hidden id="fileupload" >
    
   </form>
   <h2>{{user.staff.user.username}}</h2>
  </div>
  <div id="frame2"></div>
  
  <p><b>Role:</b>Staff</p>
   <p><b>Organization:</b>{{user.staff.organization.name}}</p>


{% else %}
{% if user.organization %}

 
  <div id="frame1" class="bg-body-tertiary">
    <img id="profile-pic" src="{{user.organization.logo.url}}"><i class="fa-solid fa-pen-to-square" id="edit-profile-pic"></i>
   
   <form enctype="multipart/form-data" method="POST" action="{% url 'profiles:edit_profile_pic' %}" hidden="true" id="profile_pic_form">
    {% csrf_token %}
   <input name="profile_pic" type="file" accept=".png" hidden id="fileupload" >
    
   </form>
   <h2>{{user.organization.user.username}}</h2>
  </div>
  <div id="frame2"></div>
  
   <p><b>Organization Name:</b>{{user.organization.name}}</p>
   <p><b>Public Key:</b>{{user.organization.public_key}}</p>


{% endif %}
{% endif %}
</div>
{% endblock content %}

profiles/templates/profiles/login.html
{% extends 'base.html' %}                         {% load crispy_forms_tags %}     
{% load static %}
{% block title %}                                 Login
{% endblock title %}   

{% block style %}
<link rel="stylesheet" href="{% static 'profiles/css/base.css' %}">
{% endblock style %}

{% block navbar %}
{% include 'profiles/navbar.html' %}
{% endblock navbar %}                                                                               {% block content %}     
<main>
	{% if msg %}
	<div class="alert alert-info" role="alert" >
		{{msg}}
	</div>
	{% endif %}
<form action="" method="POST" class="myform mt-5">
	<h1>Login</h1>
	{% csrf_token %}
	{% if error %}
	<div class="alert alert-danger" role="alert" >
		{{ error }}
	</div>
	{% endif %}
	{{login_form|crispy}}                             <button type="submit" class="btn btn-success mt-4 form-control">Login</button>
        <div class="extra-text">don't have an account? </div>             
	<a href="{% url 'profiles:signup' %}" class="btn btn-outline-success mt-4 mb-2   signup-login-a" >signup</a>
</form>
</main>

{% endblock content %}

profiles/templates/profiles/navbar.html
<nav class="navbar-expand-lg bg-body-tertiary ">
  <div class="container-fluid navcontainer">
    <a class="navbar-brand" href="#">Reports Alchemy</a>
    </div>
  </div>
</nav>

profiles/templates/profiles/signup.html
{% extends 'profiles/login.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
signup
{% endblock title %}

{% block scripts %}
<script src="{% static 'profiles/js/signup.js' %}" defer ></script>
{% endblock scripts %}

{% block content %}
<main>
<form action="" method="POST" class="myform mt-5">
	<h1>Signup</h1>
	{% csrf_token %}
	{% if  error %}
	<div class="alert alert-danger" role="alert">
		{{error}}
	</div>
	{% endif %}
	{% for field in signup_form %}
	{% if field.label == 'Public key' %}
	<div hidden="true" id="public_key_div">
		{{field|as_crispy_field}}
	</div>
	{% else %}
	
	{{field|as_crispy_field}}
	{% endif %}
	{% endfor %}

		
	<button type="submit" class="btn btn-success mt-4 form-control"> Signup </button>
	<div class="extra-text"> already have an account?</div>
	<a href="{% url 'profiles:login' %}" class="btn btn-outline-success mt-4 mb-2  form-control signup-login-a" >Login</a>
</form>
	</main>

{% endblock content %}