index/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [

        path('',views.index,name="index"),
        ]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls',namespace='index')),
    path('sales/',include('sales.urls',namespace='sales')),
    path('reports/',include('reports.urls',namespace='reports')),
    path('profiles/',include('profiles.urls',namespace='profiles')),
]

urlpatterns += static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

reports/urls.py
from django.urls import path
from . import views

app_name = "reports"

urlpatterns = [
        path('',views.ReportList.as_view(),name = 'index'),
        path('<pk>/detail/',views.ReportDetail.as_view(),name = 'detail'),
        path('save/',views.add_report,name='add_report'),
path('pdf/<pk>',views.pdf,name='pdf'),
        ]

reports/models.py
from django.db import models
from profiles.models import Staff,Organization 
from django.urls import reverse

# Create your models here.

class Report(models.Model):
    name = models.CharField(max_length=120)
    image = models.ImageField(upload_to='reports',blank=True)
    remark = models.TextField()
    author = models.ForeignKey(Staff,on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization,on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        
        return str(self.name)

    def get_absolute_url(self):

        return reverse("reports:detail",kwargs={'pk':self.pk})

    class Meta:
        ordering = ["-updated"]

reports/forms.py
from django import forms
from .models import Report

class ReportForm(forms.ModelForm):

    class Meta:
        model = Report
        fields = ["name","remark"]

reports/views.py
from django.shortcuts import render
from .models import Report
from django.views.generic import DetailView, ListView
from django.views import View
from profiles.models import Staff,Organization
from django.http import JsonResponse,FileResponse
from .utils import get_report_image, get_report_pdf, cleanup
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

@method_decorator(login_required,name="dispatch")
class ReportList(ListView):
    
    model = Report
    template_name = "reports/index.html"
    context_object_name = "reports"

    def get_queryset(self):
        try:
            qs = Report.objects.filter(organization = self.request.user.staff.organization)
        except:
            qs = Report.objects.filter(organization = self.request.user.organization)
        return qs

@method_decorator(login_required,name="dispatch")
class ReportDetail(View):

    def get(self,request,pk):
        try:
            org = request.user.staff.organization
            """ Due to configuration of the profile and custom user model, we have to try to access the organization based on the user type"""
        except:
            org = request.user.organization
        
        report = Report.objects.get(pk=pk,organization=org)
        context = {
            "report":report,
        }
        return render(request,"reports/detail.html",context)


@login_required
def pdf(request,pk):
    fd, filename= get_report_pdf(pk)
    cleanup(filename)

    return FileResponse(fd,filename=filename)

@login_required
def add_report(request):
    
    if request.headers.get("X-Requested-With")=="XMLHttpRequest":
        org = request.user.staff.organization
        name = request.POST.get('name')
        remark = request.POST.get('remark')
        image = get_report_image(request.POST.get('image'))
        author = Staff.objects.get(user=request.user)
        Report.objects.create(name=name,remark=remark,image=image,author=author,organization=org)
        

        return JsonResponse({'msg':'send'})

reports/templates/reports/detail.html
{% extends 'base.html' %}

{% block title %}
reports detail
{% endblock title %}

{% block content %}
<div class="card p-3 mb-5" >
        <img src="{{report.image.url}}" class="card-img-top pl-2 w-100 h-100" >                                              <div class="card-body">                                       <h5 class="card-title">{{report.name}}</h5>
		<strong>Remark</strong>
		<p class="card-text">{{report.remark}}</p>
        		<strong>Author</strong>
		<p class="card-text">
				{{report.author.user.username}}
		</p>
        		<strong>Created</strong>
		<p class="card-text">
				{{report.created}}
		</p>

  </div>
</div>
{% endblock content %}

reports/templates/reports/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
report list
{% endblock title %}

{% block styles %}
<link rel="stylesheet" href="{% static 'reports/style.css' %}">
{% endblock styles %}
{% block scripts %}
<script src="{% static 'reports/js/pdf.js' %}"></script>
{% endblock scripts %}

{% block content %}
{% if reports %}
<form hidden="true">
		{% csrf_token %}
</form>
{% for report in reports %}
<div class="card mb-5 p-3" >
        <img src="{{report.image.url}}" class="card-img-top pl-2 w-100 h-100" >                                              <div class="card-body">                                       <h5 class="card-title">{{report.name}}</h5>
		<strong>Remark</strong>
		<p class="card-text">{{report.remark|truncatewords:20}}</p>

    <a href="{{report.get_absolute_url}}" class="btn btn-outline-primary mt-3 w-50">Details</a>
    <a href="{% url 'reports:pdf' report.id  %}" class="btn btn-warning mt-3 pdf-btn" id="{{report.id}}">PDF</a>
  </div>
</div>
{% endfor %}
{% else %}
<div class="alert alert-warning" role="alert">
		No Reports Available
</div>
{% endif %}
{% endblock content %}