index/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [

        path('',views.index,name="index"),
        ]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls',namespace='index')),
    path('sales/',include('sales.urls',namespace='sales')),
    path('reports/',include('reports.urls',namespace='reports')),
    path('profiles/',include('profiles.urls',namespace='profiles')),
]

urlpatterns += static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
        path('accounts/login/',views.loginview,name='login'),
        path('accounts/logout/',views.logoutview,name='logout'),
        path('accounts/signup/',views.signupview,name='signup'),
        path('accounts/profile/',views.home,name='home'),
        path('accounts/profile/change_profile_pic/',views.edit_profile_pic,name="edit_profile_pic"),
        ]

sales/urls.py
from django.urls import path
from . import views
app_name = 'sales'

urlpatterns = [
        path('',views.home_view,name='home'),
        path('dashboard/',views.SalesDashboard.as_view(),name='dashboard'),
        path('sales/<pk>',views.SaleDetailView.as_view(),name='detail'),
        path('sales/upload_csv/',views.upload_csv,name="upload_csv"),

        ]

templates/base.html
 {% load static %}
<!doctype html>
  <html lang="en">
  <head>
    <!-- required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    
    <!--favicon-->
    <!--google fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia|Roboto">
    <!--font awesome icon-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
    <!--bootstrap-->
    <link rel="stylesheet"  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css">
        
    <!-- jquery-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js" defer ></script>
    
    <!-- dropzone js and css -->
    <link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.3/dropzone.min.css">
    <script src=" https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.3/dropzone.min.js"></script>
    <!-- custom js and css-->
    <link rel="stylesheet" href="{% static 'sales/css/style.css' %}">
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
    <link rel="stylesheet" href="{% static '/css/navbar.css' %}">
    <script src="{% static 'js/navbar.js' %}" defer></script>
    
    {% block scripts %}
    {% endblock scripts %}
    {% block style %}
    {% endblock style %}
    
    <title>Report App|{% block title %}{% endblock title %}</title>
    
  </head>
  <body>

   {% block navbar %}
   {% include "navbar.html" %}
   {% endblock navbar %}

    <div class="cont  mb-3">
      {% block content %}
      {% endblock content %}
      
    </div>
    
    <!-- bootstrap js-->
    <script type="application/javascript"src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
    
  </body>
  </html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-secondary fixed-top" id="top-navbar">
  <div class="container-fluid">
    <a class="navbrand-R">R</a>
   <a class="navbar-brand navbrand" style="color:green;" href="/">eports Alchemy</a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'sales:dashboard' %}">Dashboard</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sales:home' %}">Sales</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'reports:index' %}">Reports</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profiles:home' %}" hr>Profile</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- Custom Nav-->
<nav class="custom-navbar navbar-expand-lg fixed-top ">
  <div class="container-fluid navcontainer">
    <div class="frame1">
      <b>  
        {{user.organization.name}}     {{user.staff.organization.name}}
      </b>
     
    
    </div>
    <div class="frame2">
      {% if user.is_authenticated %}
      <a href="{% url 'profiles:home' %}"><img src="{{user.staff.avatar.url}}{{user.organization.logo.url}}"></a>
      <a href="{% url 'profiles:logout' %}" class="btn btn-outline-success">logout</a>
      {% else %}
      <img src="/media/no_headshot.png" style="filter:grayscale(100%);">
      <a href="{% url 'profiles:login' %}" class="btn btn-success">login</a>
      {% endif %}
    </div>
  </div>
</nav>